<?php
/* Copyright (C) 2007-2017 Laurent Destailleur  <eldy@users.sourceforge.net>
 * Copyright (C) 2020 	   Arthur Croix			<arthur@code42.fr>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/**
 *   	\file       htdocs/contratplus/list.php
 *		\ingroup    contratplus
 *		\brief      List page for contratplus
 */


// Load Dolibarr environment
$res=0;
// Try main.inc.php into web root known defined into CONTEXT_DOCUMENT_ROOT (not always defined)
if (! $res && ! empty($_SERVER["CONTEXT_DOCUMENT_ROOT"])) $res=@include $_SERVER["CONTEXT_DOCUMENT_ROOT"]."/main.inc.php";
// Try main.inc.php into web root detected using web root calculated from SCRIPT_FILENAME
$tmp=empty($_SERVER['SCRIPT_FILENAME'])?'':$_SERVER['SCRIPT_FILENAME'];$tmp2=realpath(__FILE__); $i=strlen($tmp)-1; $j=strlen($tmp2)-1;
while($i > 0 && $j > 0 && isset($tmp[$i]) && isset($tmp2[$j]) && $tmp[$i]==$tmp2[$j]) { $i--; $j--; }
if (! $res && $i > 0 && file_exists(substr($tmp, 0, ($i+1))."/main.inc.php")) $res=@include substr($tmp, 0, ($i+1))."/main.inc.php";
if (! $res && $i > 0 && file_exists(dirname(substr($tmp, 0, ($i+1)))."/main.inc.php")) $res=@include dirname(substr($tmp, 0, ($i+1)))."/main.inc.php";
// Try main.inc.php using relative path
if (! $res && file_exists("../main.inc.php")) $res=@include "../main.inc.php";
if (! $res && file_exists("../../main.inc.php")) $res=@include "../../main.inc.php";
if (! $res && file_exists("../../../main.inc.php")) $res=@include "../../../main.inc.php";
if (! $res) die("Include of main fails");

require_once DOL_DOCUMENT_ROOT."/contrat/class/contrat.class.php";
require_once DOL_DOCUMENT_ROOT.'/core/class/html.formcompany.class.php';
require_once DOL_DOCUMENT_ROOT.'/core/class/html.formother.class.php';
require_once DOL_DOCUMENT_ROOT."/cron/class/cronjob.class.php";
require_once DOL_DOCUMENT_ROOT.'/core/lib/date.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/lib/company.lib.php';

dol_include_once('/contratplus/class/customcontrat.class.php');
dol_include_once('/contratplus/class/renew.class.php');
dol_include_once('/contratplus/core/function.php');
dol_include_once('/contratplus/lib/contratplus.lib.php');
dol_include_once('/contratplus/core/automatefunction.php');


// Load translation files required by the page
$langs->loadLangs(array("contratplus@contratplus","other","contracts"));

$action     = GETPOST('action', 'aZ09')?GETPOST('action', 'aZ09'):'view';				// The action 'add', 'create', 'edit', 'update', 'view', ...
$massaction = GETPOST('massaction', 'alpha');											// The bulk action (combo box choice into lists)
$show_files = GETPOST('show_files', 'int');												// Show files area generated by bulk actions ?
$confirm    = GETPOST('confirm', 'alpha');												// Result of a confirmation
$cancel     = GETPOST('cancel', 'alpha');												// We click on a Cancel button
$toselect   = GETPOST('toselect', 'array');												// Array of ids of elements selected into a list
$contextpage= GETPOST('contextpage', 'aZ')?GETPOST('contextpage', 'aZ'):'contractlist';   // To manage different context of search
$backtopage = GETPOST('backtopage', 'alpha');											// Go back to a dedicated page
$optioncss  = GETPOST('optioncss', 'aZ');												// Option for the css output (always '' except when 'print')
$op2df		= GETPOST('op2df', "alpha");
$dfmonth	= GETPOST('dfmonth', "int");
$dfyear		= GETPOST('dfyear', "int");

$id			= GETPOST('id', 'int');

// Load variable for pagination
$limit = GETPOST('limit', 'int')?GETPOST('limit', 'int'):$conf->liste_limit;
$sortfield = GETPOST('sortfield', 'alpha');
$sortorder = GETPOST('sortorder', 'alpha');
$page = GETPOST('page', 'int');
if (empty($page) || $page == -1 || GETPOST('button_search', 'alpha') || GETPOST('button_removefilter', 'alpha') || (empty($toselect) && $massaction === '0')) { $page = 0; }     // If $page is not defined, or '' or -1 or if we click on clear filters or if we select empty mass action
$offset = $limit * $page;
$pageprev = $page - 1;
$pagenext = $page + 1;
//if (! $sortfield) $sortfield="p.date_fin";
//if (! $sortorder) $sortorder="DESC";

// Initialize technical objects
$object = new CustomContrat($db);
$form = new Form($db);
$formother = new FormOther($db);
$extrafields = new ExtraFields($db);
$diroutputmassaction = $conf->constratplus->dir_output . '/temp/massgeneration/'.$user->id;
$hookmanager->initHooks(array($contextpage));     // Note that conf->hooks_modules contains array
// Fetch optionals attributes and labels
$extralabels = $extrafields->fetch_name_optionals_label('contrat');	// Load $extrafields->attributes['myobject']
$search_array_options = $extrafields->getOptionalsFromPost($object->table_element, '', 'search_');

$societe = array('rowid', 'nom');
$contrat = array('rowid', 'ref', 'ref_customer', 'ref_supplier', 'date_contrat', 'statut');
$other = array('fk_user');

// Default sort order (if not yet defined by previous GETPOST)
if (! $sortfield) $sortfield=(in_array(key($object->fields), $societe) ? 's.' : (in_array(key($object->fields), $contrat) ? 'c.' : '')).key($object->fields);   // Set here default search field. By default 1st field in definition.
if (! $sortorder) $sortorder="ASC";

// Security check
if (empty($conf->contratplus->enabled)) accessforbidden('Module not enabled');
$socid=0;
if ($user->societe_id > 0)	// Protection if external user
{
	//$socid = $user->societe_id;
	accessforbidden();
}
//$result = restrictedArea($user, 'contratplus', $id, '');


// Initialize array of search criterias
$search_all=trim(GETPOST("search_all", 'alpha'));
$search=array();
foreach($object->fields as $key => $val)
{
	if (GETPOST('search_'.$key, 'alpha')) $search[$key]=GETPOST('search_'.$key, 'alpha');
}
if ($search['month'] && $search['year']) {
	if ($search['month'] > 12) {
		$search['month'] = 12;
	}
	$search['date_contrat'] = " BETWEEN '".$db->idate(dol_get_first_day($search['year'], $search['month'], false))."' AND '".$db->idate(dol_get_last_day($search['year'], $search['month'], false))."'";
}
$othersearchfields = array('op2df', 'dfyear', 'dfmonth', 'month', 'year');
foreach ($othersearchfields as $key) {
	if (GETPOST('search_'.$key, 'alpha')) $search[$key]=GETPOST('search_'.$key, 'alpha');
}
if(GETPOST('search_cli_four')!='') $search['cli_four']=GETPOST('search_cli_four');
else $search['cli_four'] = -1;

// List of fields to search into when doing a "search in all"
$fieldstosearchall = array();

foreach($object->fields as $key => $val)
{
	if ($val['searchall']) $fieldstosearchall[(in_array($key, $societe) ? 's.' : (in_array($key, $contrat) ? 'c.' : '')).$key]=$val['label'];
}

// Definition of fields for list
$arrayfields=array();
foreach ($object->fields as $key => $val)
{
	// If $val['visible']==0, then we never show the field
	if (!empty($val['visible'])) $arrayfields[(in_array($key, $societe) ? 's.' : (in_array($key, $contrat) ? 'c.' : '')).$key] = array('label'=>$val['label'], 'checked'=>(($val['visible'] < 0) ? 0 : 1), 'enabled'=>($val['enabled'] && ($val['visible'] != 3)), 'position'=>$val['position']);
}
// Extra fields
if (is_array($extrafields->attributes[$object->table_element]['label']) && count($extrafields->attributes[$object->table_element]['label']) > 0)
{
	foreach ($extrafields->attributes[$object->table_element]['label'] as $key => $val)
	{
		if (!empty($extrafields->attributes[$object->table_element]['list'][$key])) {
			$arrayfields["ef." . $key] = array(
				'label' => $extrafields->attributes[$object->table_element]['label'][$key],
				'checked' => (($extrafields->attributes[$object->table_element]['list'][$key] < 0) ? 0 : 1),
				'position' => $extrafields->attributes[$object->table_element]['pos'][$key],
				'enabled' => (abs($extrafields->attributes[$object->table_element]['list'][$key]) != 3 && $extrafields->attributes[$object->table_element]['perms'][$key])
			);
		}
	}
}
$object->fields = dol_sort_array($object->fields, 'position');
$arrayfields = dol_sort_array($arrayfields, 'position');

// Cron fetch
$cron = new CronJob($db);

$idcron = getCronIdByLabel('ContratPlusCron');
$cron->fetch($idcron);
/*
 * Actions
 */

if (GETPOST('cancel', 'alpha')) { $action='list'; $massaction=''; }
if (!GETPOST('confirmmassaction', 'alpha') && $massaction != 'presend' && $massaction != 'confirm_presend') { $massaction = ''; }

if ($action == 'delete' && GETPOST('confirm', 'string') == 'yes') {
	$rowcontrat = new CustomContrat($db);
	$res = 0;
	foreach ($toselect as $key => $val) {
		$rowcontrat->fetch((int)$val);
		if ($rowcontrat->delete($user) > 0) {
			$res++;
		}
	}
	$toselect = array();
	if ($res == 1) {
		setEventMessages($langs->trans('RecordDeleted'), null, 'mesgs');
	} else if ($res > 1) {
		setEventMessages($langs->trans('RecordsDeleted', $res), null, 'mesgs');
	}
}

if ($action == "confirm_renewall")
{
	$option = getOption();
	// get selected contract
	$selected = unserialize(GETPOST('selected'));
	if ($selected != null) {
		$renew = new Renew($db, $conf, $user);
		$res = $renew->renewAll($option, $selected);
		if ($res < 0)
			setEventMessages($langs->trans('ErrorRenewal'), '', 'errors');
	}
	else
	{
		setEventMessages($langs->trans('NoContractSelected'), '', 'errors');
	}
	$param_url=GETPOST('param_url');
	exit(header("Location: ".$_SERVER['PHP_SELF'].$param_url));
}

if ($action == "confirm_automate")
{
	// get selected contract
	$selected = unserialize(GETPOST('selected'));
	$automated = array();
	$notautomated = array();

	// divide automated / not automated in selected contracts
	foreach ($selected as $id)
	{
		if (isAutomatedId(intval($id)))
			$automated[] = $id;
		else
			$notautomated[] = $id;
	}

	if ($automated)
		setUnautomated($automated);

	if ($notautomated)
		setAutomated($notautomated, dol_now());

	setEventMessages($langs->trans('ContractsAutomated'), '', 'mesgs');

	$param_url=GETPOST('param_url');
	exit(header("Location: ".$_SERVER['PHP_SELF'].$param_url));
}

if ($action == "activate" || $action == "unactivate")
{
	if ($action == "activate")
	{
		$text = $langs->trans("ActivateContractConfirmation");
		$title = $langs->trans("ActivateContractForCron");
		$action = "confirm_activate";
	} else {
		$text = $langs->trans("UnactivateContractConfirmation");
		$title = $langs->trans("UnactivateContractForCron");
		$action = "confirm_unactivate";
	}
	$url = $_SERVER["PHP_SELF"].'?id='.GETPOST('id');
	print $form->formconfirm($url, $title, $text, $action, '', 0, 1);
}

if ($action == "confirm_activate")
{
	$id = array(GETPOST('id'));
	setAutomated($id, dol_now());
	setEventMessages($langs->trans('ContractSelectedForAutoRenew'), '', 'mesgs');
	$param_url=GETPOST('param_url');
	exit(header("Location: ". $_SERVER['PHP_SELF'].$param_url));
}

if ($action == "confirm_unactivate")
{
	$id = array(GETPOST('id'));
	setUnautomated($id, dol_now());
	setEventMessages($langs->trans('ContractDeselectedForAutoRenew'), '', 'mesgs');
	$param_url=GETPOST('param_url');
	exit(header("Location: ".$_SERVER['PHP_SELF'].$param_url));
}


$parameters=array();
$reshook=$hookmanager->executeHooks('doActions', $parameters, $object, $action);    // Note that $action and $object may have been modified by some hooks
if ($reshook < 0) setEventMessages($hookmanager->error, $hookmanager->errors, 'errors');

if (empty($reshook))
{
	// Selection of new fields
	include DOL_DOCUMENT_ROOT.'/core/actions_changeselectedfields.inc.php';

	// Purge search criteria
	if (GETPOST('button_removefilter_x', 'alpha') || GETPOST('button_removefilter.x', 'alpha') ||GETPOST('button_removefilter', 'alpha')) // All tests are required to be compatible with all browsers
	{
		foreach($object->fields as $key => $val)
		{
			$search[$key]='';
		}
		foreach($othersearchfields as $key) {
			$search[$key]='';
		}
		$search['cli_four'] = -1;
		$toselect='';
		$search_array_options=array();
	}
	if (GETPOST('button_removefilter_x', 'alpha') || GETPOST('button_removefilter.x', 'alpha') || GETPOST('button_removefilter', 'alpha')
		|| GETPOST('button_search_x', 'alpha') || GETPOST('button_search.x', 'alpha') || GETPOST('button_search', 'alpha'))
	{
		$massaction='';     // Protection to avoid mass action if we force a new search during a mass action confirmation
	}

	// Mass actions
	$objectclass='ContratPlus';
	$objectlabel='ContratPlus';
	$permtoread = $user->rights->contratplus->read;
	$permtodelete = $user->rights->contratplus->delete;
	$uploaddir = $conf->contratplus->dir_output;
	include DOL_DOCUMENT_ROOT.'/core/actions_massactions.inc.php';
}


/*
 * View
 */

$form=new Form($db);


$now=dol_now();

$help_url='';
$title = $langs->trans('ListOf', $langs->transnoentitiesnoconv("ContratPlus"));


// Build and execute select
// --------------------------------------------------------------------
$sql = 'SELECT ';
foreach($societe as $key)
{
	if ($key == 'rowid') {
		$sql.= 's.rowid as socid, ';
	} else {
		$sql.= 's.'.$key.', ';
	}
}
foreach($contrat as $key) {
	$sql.= 'c.'.$key.', ';
}
// lower_planned_end_date is a parameter later used in the list
$sql.= 'MIN(IF(cd.statut=4, cd.date_fin_validite, null)) as lower_planned_end_date, ';
// Check the number of initial, running, expired or closed services
$sql.= 'SUM(IF(cd.statut=0,1,0)) as nb_initial, '; // Initial
$sql.= 'SUM(IF(cd.statut=4 AND (cd.date_fin_validite IS NULL OR cd.date_fin_validite >= \''.$db->idate($now).'\'),1,0)) as nb_running, '; // Running
$sql.= 'SUM(IF(cd.statut=4 AND (cd.date_fin_validite IS NOT NULL AND cd.date_fin_validite < \''.$db->idate($now).'\'),1,0)) as nb_expired, '; // Expired
$sql.= 'SUM(IF(cd.statut=5,1,0)) as nb_closed, ';
$sql.= 'SUM(IF(cd.statut=4 AND (cd.date_fin_validite IS NOT NULL AND cd.date_fin_validite < \''.$db->idate($now - $conf->contrat->services->expires->warning_delay).'\'),1,0)) as nb_late, '; // Late
// Add fields from extrafields
if (! empty($extrafields->attributes[$object->table_element]['label']))
	foreach ($extrafields->attributes[$object->table_element]['label'] as $key => $val) $sql.=($extrafields->attributes[$object->table_element]['type'][$key] != 'separate' ? "ef.".$key.' as options_'.$key.', ' : '');
// Add fields from hooks
$parameters=array();
$reshook=$hookmanager->executeHooks('printFieldListSelect', $parameters, $object);    // Note that $action and $object may have been modified by hook
$sql.=preg_replace('/^,/', '', $hookmanager->resPrint);
$sql =preg_replace('/,\s*$/', '', $sql);
$sql.= " FROM ".MAIN_DB_PREFIX."societe as s";
if ($search['fk_user']) {
	$sql.= ", ".MAIN_DB_PREFIX."societe_commerciaux as sc";
}
$sql.= ", ".MAIN_DB_PREFIX.$object->table_element." as c";
$sql.= " LEFT JOIN llx_contratdet as cd ON c.rowid = cd.fk_contrat";
// To search the tags of a product/service linked to a contract
if ($search['product_category']) {
	$sql.= " LEFT JOIN ".MAIN_DB_PREFIX."categorie_product as cp ON cp.fk_product = cd.fk_product";
}
// Get linked contacts on contracts
if (is_array($extrafields->attributes[$object->table_element]['label']) && count($extrafields->attributes[$object->table_element]['label'])) $sql.= " LEFT JOIN ".MAIN_DB_PREFIX.$object->table_element."_extrafields as ef on c.rowid = ef.fk_object";
if ($object->ismultientitymanaged == 1) $sql.= " WHERE c.entity IN (".getEntity($object->element).")";
else $sql.=" WHERE 1 = 1";
$sql.= ' AND c.fk_soc = s.rowid';
if ($search['fk_user']) {
	$sql.= ' AND s.rowid = sc.fk_soc';
}

foreach($search as $key => $val)
{
	if ($key == 'status') {
		if ($search[$key] != null) {
			// Due to arrayofkeyval that needs 0 as default value, the element were updated
			$sql.= ' AND c.statut = '.((integer)$search[$key] - 1);
		}
		continue;
	}
	// To search the tags of a product/service linked to a contract
	if ($search['product_category'] && $search['product_category'] != -1) {
		$sql.= " AND cp.fk_categorie = ".$search['product_category'];
		continue;
	}
	if (in_array($key, array('op2df', 'dfyear', 'dfmonth', 'cli_four', 'product_category'))) continue;
	if ($key == 'date_contrat') {
		$sql.= ' AND c.date_contrat'.$search['date_contrat'];
		continue;
	}
	if ($key == 'month') {
		if ($search[$key] != null) {
			$sql.= ' AND c.date_contrat LIKE "%-'.$search[$key].'-%"';
			continue;
		}
	}
	if ($key == 'year') {
		if ($search[$key] != null) {
			$sql.= ' AND c.date_contrat LIKE "'.$search[$key].'-%"';
			continue;
		}
	}
	$mode_search=(($object->isInt($object->fields[$key]) || $object->isFloat($object->fields[$key])) ? 1 : 0);
	if ($search[$key] != '') $sql.=natural_search($key, $search[$key], (($key == 'status')?2:$mode_search));
}
if ($conf->global->CONTRATPLUS_SUPPLIER_CONTRACT)
{
	if ($search['cli_four'] == '1')
		$sql .= " AND ef.supplier_contract = 1";
	elseif ($search['cli_four'] == '0')
		$sql .= " AND ef.supplier_contract IS NULL";
} else {
	$sql .= " AND ef.supplier_contract IS NULL";
}
if ($search_all) $sql.= natural_search(array_keys($fieldstosearchall), $search_all);
// Add where from extra fields
include DOL_DOCUMENT_ROOT.'/core/tpl/extrafields_list_search_sql.tpl.php';
// Add where from hooks
$parameters=array();
$reshook=$hookmanager->executeHooks('printFieldListWhere', $parameters, $object);    // Note that $action and $object may have been modified by hook
$sql.=$hookmanager->resPrint;

$sql.= ' GROUP BY ';
foreach($societe as $key)
{
	if ($key == 'rowid') {
		$sql.= 'socid, ';
	} else {
		$sql.= 's.'.$key.', ';
	}
}
foreach($contrat as $key) {
	$sql.= 'c.'.$key.', ';
}
foreach ($extrafields->attributes[$object->table_element]['label'] as $key => $val) $sql.=($extrafields->attributes[$object->table_element]['type'][$key] != 'separate' ? 'options_'.$key.', ' : '');
$sql =preg_replace('/,\s*$/', '', $sql);

if ($search['dfyear'] > 0 && $search['op2df'])
{
	if ($search['op2df'] == '<=') $sql.= " HAVING MIN(".$db->ifsql("cd.statut=4", "cd.date_fin_validite", "null").") <= '".$db->idate(dol_get_last_day($search['dfyear'], $search['dfmonth'], false))."'";
	elseif ($search['op2df'] == '>=') $sql.= " HAVING MIN(".$db->ifsql("cd.statut=4", "cd.date_fin_validite", "null").") >= '".$db->idate(dol_get_first_day($search['dfyear'], $search['dfmonth'], false))."'";
	else $sql.= " HAVING MIN(".$db->ifsql("cd.statut=4", "cd.date_fin_validite", "null").") <= '".$db->idate(dol_get_last_day($search['dfyear'], $search['dfmonth'], false))."' AND MIN(".$db->ifsql("cd.statut=4", "cd.date_fin_validite", "null").") >= '".$db->idate(dol_get_first_day($search['dfyear'], $search['dfmonth'], false))."'";
}


$sql.=$db->order($sortfield, $sortorder);



// Count total nb of records
$nbtotalofrecords = '';
if (empty($conf->global->MAIN_DISABLE_FULL_SCANLIST))
{
	$resql = $db->query($sql);
	$nbtotalofrecords = $db->num_rows($resql);
	if (($page * $limit) > $nbtotalofrecords)	// if total of record found is smaller than page * limit, goto and load page 0
	{
		$page = 0;
		$offset = 0;
	}
}
// if total of record found is smaller than limit, no need to do paging and to restart another select with limits set.
if (is_numeric($nbtotalofrecords) && $limit > $nbtotalofrecords)
{
	$num = $nbtotalofrecords;
}
else
{
	$sql.= $db->plimit($limit+1, $offset);

	$resql=$db->query($sql);
	if (! $resql)
	{
		dol_print_error($db);
		exit;
	}

	$num = $db->num_rows($resql);
	$option = getOption($db);
}

// Direct jump if only one record found
if ($num == 1 && ! empty($conf->global->MAIN_SEARCH_DIRECT_OPEN_IF_ONLY_ONE) && $search_all)
{
	$obj = $db->fetch_object($resql);
	$id = $obj->rowid;
	header("Location: ".dol_buildpath('/contratplus/card.php', 1).'?id='.$id);
	exit;
}


// Output page
// --------------------------------------------------------------------

llxHeader('', $title, $help_url);

// Example : Adding jquery code
print '<script type="text/javascript" language="javascript">
jQuery(document).ready(function() {
	function init_myfunc()
	{
		jQuery("#myid").removeAttr(\'disabled\');
		jQuery("#myid").attr(\'disabled\',\'disabled\');
	}
	init_myfunc();
	jQuery("#mybutton").click(function() {
		init_myfunc();
	});
});
</script>';

$arrayofselected=is_array($toselect)?$toselect:array();

$param='';
if (! empty($contextpage) && $contextpage != $_SERVER["PHP_SELF"]) $param.='&contextpage='.urlencode($contextpage);
if ($limit > 0 && $limit != $conf->liste_limit) $param.='&limit='.urlencode($limit);
foreach($search as $key => $val)
{
	if (is_array($search[$key]) && count($search[$key])) foreach($search[$key] as $skey) $param.='&search_'.$key.'[]='.urlencode($skey);
	else $param.= '&search_'.$key.'='.urlencode($search[$key]);
}
if ($optioncss != '')     $param.='&optioncss='.urlencode($optioncss);
// Add $param from extra fields
include DOL_DOCUMENT_ROOT.'/core/tpl/extrafields_list_search_param.tpl.php';

/*
 * Massactions
 */

// check supplier authorisation
$supplier_ok = true;
if ($conf->global->CONTRATPLUS_SUPPLIER_CONTRACT == 1)
{
	$supplier_ok = false;
	if ($user->rights->fournisseur->facture->lire
		&& $user->rights->fournisseur->facture->creer
		&& $user->rights->fournisseur->facture->creer)
		$supplier_ok = true;
}

// check contrat plus configuration
$mailConfigured = true;
if ($conf->global->CONTRATPLUS_IS_MAIL_CONFIGURED == 0 && $option >= 4)
	$mailConfigured = false;

$arrayofmassactions = array(
	'predelete'=>'<span class="fa fa-trash paddingrightonly"></span>'.$langs->trans("Delete")
);
if (isAuthorize($option, $user) && $supplier_ok && $user->rights->contratplus->renew->all
	&& $conf->global->CONTRATPLUS_IS_CONFIGURED == 1 && $mailConfigured)
	$arrayofmassactions['mass_renewall'] = $langs->trans("RenewContrat");

if ($cron->status == 1 && $user->rights->contratplus->renew->auto == 1)
	$arrayofmassactions['mass_automate'] = $langs->trans("AddAutomated");

if ($massaction == 'mass_renewall')
{
	$text = getRenewalAllConfirmation($toselect, $db, $langs, $conf);
	$url = $_SERVER["PHP_SELF"].'?param_url='.urlencode($param_url);
	// serialize toselect array to send it by GET
	print $form->formconfirm($url, $langs->trans("ValidRenewal"), $text, "confirm_renewall", array(array('name'=>'selected','type'=>'hidden','value'=>serialize($toselect))), '', 1);
}

if ($massaction == 'mass_automate')
{
	$text = getAutomateConfirmation($toselect);
	$url = $_SERVER["PHP_SELF"].'?param_url='.urlencode($param_url);
	// serialize toselect array to send it by GET
	print $form->formconfirm($url, $langs->trans("ValidAutomate"), $text, "confirm_automate", array(array('name'=>'selected','type'=>'hidden','value'=>serialize($toselect))), '', 1);
}


if (GETPOST('nomassaction', 'int') || in_array($massaction, array('predelete'))) $arrayofmassactions=array();
$massactionbutton=$form->selectMassAction('', $arrayofmassactions);

print '<form method="POST" id="searchFormList" action="'.$_SERVER["PHP_SELF"].'">';
if ($optioncss != '') print '<input type="hidden" name="optioncss" value="'.$optioncss.'">';
print '<input type="hidden" name="token" value="'.$_SESSION['newtoken'].'">';
print '<input type="hidden" name="formfilteraction" id="formfilteraction" value="list">';
print '<input type="hidden" name="action" value="list">';
print '<input type="hidden" name="sortfield" value="'.$sortfield.'">';
print '<input type="hidden" name="sortorder" value="'.$sortorder.'">';
print '<input type="hidden" name="page" value="'.$page.'">';
print '<input type="hidden" name="contextpage" value="'.$contextpage.'">';

print_barre_liste($title, $page, $_SERVER["PHP_SELF"], $param, $sortfield, $sortorder, $massactionbutton, $num, $nbtotalofrecords, 'title_companies', 0, $newcardbutton, '', $limit);

/**
 * Infobox contratplus configuration
 */

print '<table class="noborder cp-infobox" width="100%">';

print '<tr class="liste_titre"><td colspan="2"><i class="fa fa-info-circle" aria-hidden="true" style="margin-left: 2%"></i> '.$langs->trans('RenewContratinfo').'</td>';
print '<td align="right" width="2%"><a href="'.dol_buildpath('/contratplus/admin/config.php', 1).'">'.img_picto("title_setup", 'title_setup', 'style=width:25px');
print '</td></tr>';

print '<tr class="impair"><td width="30%"><i>'.$langs->trans('ModeSelect');
print '</i></td><td colspan="2" align="left"><b>'.$conf->global->CONTRATPLUS_OPTION.' (';
switch ($conf->global->CONTRATPLUS_OPTION) {
	case 1 : print $langs->trans('CPMode1');
		break;
	case 2 : print $langs->trans('CPMode2');
		break;
	case 3 : print $langs->trans('CPMode3');
		break;
	case 4 : print $langs->trans('CPMode4');
		break;
}
print ')';
print '</b></td></tr>';

print '<tr class="impair"><td><i>'.$langs->trans('ContratPlusDateStart');
print '</i></td><td colspan="2" align="left"><b>'.dol_print_date($conf->global->CONTRATPLUS_DATE_START);
print '</b></td></tr>';

print '<tr class="impair"><td><i>'.$langs->trans('ContratPlusDateEnd');
print '</i></td><td colspan="2" align="left"><b>'.dol_print_date($conf->global->CONTRATPLUS_DATE_END);
print '</b></td></tr>';

print '<tr class="impair"><td><i>'.$langs->trans('ContratPlusBillDate');
print '</i></td><td colspan="2" align="left"><b>'.dol_print_date($conf->global->CONTRATPLUS_BILL_DATE);
print '</b></td></tr>';

print '</table>';

/**
 * End infobox contratplus configuration
 */

// Add code for pre mass action (confirmation or email presend form)
$topicmail="SendMyObjectRef";
$modelmail="myobject";
$objecttmp=new CustomContrat($db);
$staticcontratligne=new CustomContratLigne($db);
$socstatic = new Societe($db);
$trackid='xxxx'.$object->id;
include DOL_DOCUMENT_ROOT.'/core/tpl/massactions_pre.tpl.php';

if ($search_all)
{
	foreach($fieldstosearchall as $key => $val) $fieldstosearchall[$key]=$langs->trans($val);
	print '<div class="divsearchfieldfilter">'.$langs->trans("FilterOnInto", $search_all) . join(', ', $fieldstosearchall).'</div>';
}

$moreforfilter = '';
// If the user can view prospects other than his
fillMoreForFilterForUser($search, $moreforfilter);

$parameters=array();
$reshook=$hookmanager->executeHooks('printFieldPreListTitle', $parameters, $object);    // Note that $action and $object may have been modified by hook
if (empty($reshook)) $moreforfilter .= $hookmanager->resPrint;
else $moreforfilter = $hookmanager->resPrint;

if (! empty($moreforfilter))
{
	print '<div class="liste_titre liste_titre_bydiv centpercent">';
	print $moreforfilter;
	print '</div>';
}

$varpage=empty($contextpage)?$_SERVER["PHP_SELF"]:$contextpage;
$selectedfields=$form->multiSelectArrayWithCheckbox('selectedfields', $arrayfields, $varpage);	// This also change content of $arrayfields
$selectedfields.=($massactionbutton ? $form->showCheckAddButtons('checkforselect', 1) : '');

print '<div class="div-table-responsive">';		// You can use div-table-responsive-no-min if you dont need reserved height for your table
print '<table class="tagtable liste'.($moreforfilter?" listwithfilterbefore":"").'">'."\n";

// Fields title label
// --------------------------------------------------------------------
print '<tr class="liste_titre">';
print '<th class="liste_titre" align="middle"></th>';

foreach($object->fields as $key => $val)
{
	$cssforfield=(empty($val['css'])?'':$val['css']);
	if ($key == 'status') $cssforfield.=($cssforfield?' ':'').'center';
	elseif (in_array($val['type'], array('date','datetime','timestamp'))) $cssforfield.=($cssforfield?' ':'').'center';
	elseif (in_array($val['type'], array('timestamp'))) $cssforfield.=($cssforfield?' ':'').'nowrap';
	elseif (in_array($val['type'], array('double(24,8)', 'double(6,3)', 'integer', 'real', 'price'))) $cssforfield.=($cssforfield?' ':'').'right';
	if (! empty($arrayfields[(in_array($key, $societe) ? 's.' : (in_array($key, $contrat) ? 'c.' : '')).$key]['checked']))
	{
		if (in_array($key, array('fk_user', 'status'))) {
			print '<th class="liste_titre" align="'.$cssforfield.'">'.$langs->trans($val['label']).'</th>';
		} elseif ($key == 'statuslist') {
			print '<th class="liste_titre" colspan="8" align="middle">'.$langs->trans('ServicesNumber').'</th>';
		} elseif ($key == 'thirdparty_mail') {
			print '<th class="liste_titre" align="center">'.img_picto($langs->trans("MailTitle"), dol_buildpath('/contratplus/img/mail_16.png', 1), '', 1).'</th>';
		} elseif ($key == 'cron_status') {
			print '<th class="liste_titre" align="center">'.img_picto($langs->trans("Automated"), dol_buildpath('/contratplus/img/cron_24.png', 1), '', 1).'</th>';
		} elseif ($key == 'private_note_display') {
			print '<th class="liste_titre"></th>';
		} elseif ($key == 'assoc_thirdparty_comm_closed') {
			print '<th class="liste_titre" align="center">'.img_picto($langs->trans("AssocThirdPartyCommClosed"), dol_buildpath('/contratplus/img/comm_20.png', 1), '', 1).'</th>';;
		} else {
			print getTitleFieldOfList($arrayfields[(in_array($key, $societe) ? 's.' : (in_array($key, $contrat) ? 'c.' : '')).$key]['label'], 0, $_SERVER['PHP_SELF'], (in_array($key, $societe) ? 's.' : (in_array($key, $contrat) ? 'c.' : '')).$key, '', $param, ($cssforfield?'class="'.$cssforfield.'"':''), $sortfield, $sortorder, ($cssforfield?$cssforfield.' ':''))."\n";
		}
	}
}
// Extra fields
include DOL_DOCUMENT_ROOT.'/core/tpl/extrafields_list_search_title.tpl.php';
// Hook fields
$parameters=array('arrayfields'=>$arrayfields,'param'=>$param,'sortfield'=>$sortfield,'sortorder'=>$sortorder);
$reshook=$hookmanager->executeHooks('printFieldListTitle', $parameters, $object);    // Note that $action and $object may have been modified by hook
print $hookmanager->resPrint;
// Action column
print getTitleFieldOfList($selectedfields, 0, $_SERVER["PHP_SELF"], '', '', '', '', $sortfield, $sortorder, 'center maxwidthsearch ')."\n";
print '</tr>'."\n";


// Fields title search
// --------------------------------------------------------------------
print '<tr class="liste_titre">';
print '<td class="liste_titre" align="middle">';
foreach($object->fields as $key => $val)
{
	$cssforfield=(empty($val['css'])?'':$val['css']);
	if ($key == 'status') $cssforfield.=($cssforfield?' ':'').'center';
	elseif (in_array($val['type'], array('date','datetime','timestamp'))) $cssforfield.=($cssforfield?' ':'').'center';
	elseif (in_array($val['type'], array('timestamp'))) $cssforfield.=($cssforfield?' ':'').'nowrap';
	elseif (in_array($val['type'], array('double(24,8)', 'double(6,3)', 'integer', 'real', 'price'))) $cssforfield.=($cssforfield?' ':'').'right';
	if (! empty($arrayfields[(in_array($key, $societe) ? 's.' : (in_array($key, $contrat) ? 'c.' : '')).$key]['checked']))
	{
		if (in_array($key, array('thirdparty_mail', 'cron_status', 'private_note_display', 'assoc_thirdparty_comm_closed'))) {
			print '<td class="liste_titre"></td>';
		} elseif ($val['type'] == 'date' && $key != 'lower_planned_end_date')  {
			// Date contract
			print '<td class="liste_titre center nowraponall">';
			//print $langs->trans('Month').': ';
			if (! empty($conf->global->MAIN_LIST_FILTER_ON_DAY)) print '<input class="flat width25 valignmiddle" type="text" maxlength="2" name="day" value="'.$day.'">';
			print '<input class="flat width25 valignmiddle" type="text" maxlength="2" name="search_month" value="'.$search['month'].'">';
			//print '&nbsp;'.$langs->trans('Year').': ';
			$syear = $search['year'];
			print $formother->selectyear($syear, 'search_year', 1, 20, 5);
			print '</td>';
		} elseif ($key == 'lower_planned_end_date') {
			print '<td class="liste_titre nowraponall" align="center">';
			$arrayofoperators=array('0'=>'','='=>'=','<='=>'<=','>='=>'>=');
			print $form->selectarray('search_op2df', $arrayofoperators, $search['op2df'], 0);
			print '</br>';
			print $formother->select_month($search['dfmonth'], 'search_dfmonth', 1, 0, 'valignmiddle');
			print ' ';
			$formother->select_year($search['dfyear'], 'search_dfyear', 1, 20, 5, 0, 0, '', 'valignmiddle');
			print '</td>';
		} elseif ($key == 'statuslist') {
			print_liste_field_titre($staticcontratligne->LibStatut(0, 3), '', '', '', '', 'width="16"');
			print_liste_field_titre($staticcontratligne->LibStatut(4, 3, 0), '', '', '', '', 'width="16"');
			print_liste_field_titre($staticcontratligne->LibStatut(4, 3, 1), '', '', '', '', 'width="16"');
			print_liste_field_titre($staticcontratligne->LibStatut(5, 3), '', '', '', '', 'width="16"');
			print '<td class="liste_titre" colspan="4" align="center"></td>';
		} else {
			print '<td class="liste_titre'.($cssforfield?' '.$cssforfield:'').'">';
			if (is_array($val['arrayofkeyval'])) print $form->selectarray('search_'.$key, $val['arrayofkeyval'], $search[$key], $val['notnull'], 0, 0, '', 0, 0, 0, '', 'maxwidth75');
			else print '<input type="text" class="flat maxwidth75" name="search_'.$key.'" value="'.dol_escape_htmltag($search[$key]).'">';
			print '</td>';
		}
	}
}
// Extra fields
include DOL_DOCUMENT_ROOT.'/core/tpl/extrafields_list_search_input.tpl.php';

// Fields from hook
$parameters=array('arrayfields'=>$arrayfields);
$reshook=$hookmanager->executeHooks('printFieldListOption', $parameters, $object);    // Note that $action and $object may have been modified by hook
print $hookmanager->resPrint;
// Action column
print '<td class="liste_titre maxwidthsearch">';
$searchpicto=$form->showFilterButtons();
print $searchpicto;
print '</td>';
print '</tr>'."\n";


// Detect if we need a fetch on each output line
$needToFetchEachLine=0;
if (is_array($extrafields->attributes[$object->table_element]['computed']) && count($extrafields->attributes[$object->table_element]['computed']) > 0)
{
	foreach ($extrafields->attributes[$object->table_element]['computed'] as $key => $val)
	{
		if (preg_match('/\$object/', $val)) $needToFetchEachLine++;  // There is at least one compute field that use $object
	}
}


// Loop on record
// --------------------------------------------------------------------
$i=0;
$totalarray=array();
while ($i < min($num, $limit))
{
	$obj = $db->fetch_object($resql);
	if (empty($obj)) break;		// Should not happen

	// Store properties in $object
	$object->id = $obj->rowid;

	foreach($object->fields as $key => $val)
	{
		if (property_exists($obj, $key)) $object->$key = $obj->$key;
	}
	$object->statut = $obj->statut;

	// Show here line of result
	print '<tr class="oddeven">';
	showContractLinePicto($obj, $socstatic);
	foreach($object->fields as $key => $val)
	{
		$cssforfield=(empty($val['css'])?'':$val['css']);
		if (in_array($val['type'], array('date','datetime','timestamp'))) $cssforfield.=($cssforfield?' ':'').'center';
		elseif ($key == 'status') $cssforfield.=($cssforfield?' ':'').'center';

		if (in_array($val['type'], array('timestamp'))) $cssforfield.=($cssforfield?' ':'').'nowrap';
		elseif ($key == 'ref') $cssforfield.=($cssforfield?' ':'').'nowrap';

		if (in_array($val['type'], array('double(24,8)', 'double(6,3)', 'integer', 'real', 'price')) && $key != 'status') $cssforfield.=($cssforfield?' ':'').'right';

		if (! empty($arrayfields[(in_array($key, $societe) ? 's.' : (in_array($key, $contrat) ? 'c.' : '')).$key]['checked']))
		{
			if (!in_array($key, array('statuslist', 'thirdparty_mail', 'cron_status', 'private_note_display', 'assoc_thirdparty_comm_closed'))) {
				print '<td'.($cssforfield ? ' class="'.$cssforfield.'"' : '').'>';
			}
			if ($key == 'status') print $object->getLibStatut(2);
			elseif ($key == 'nom') print $socstatic->getNomUrl(1);
			elseif ($key == 'fk_user') printSellRepresentative($obj, $socstatic);
			elseif ($key == 'statuslist') {
				print '<td align="center">'.($obj->nb_initial>0?$obj->nb_initial:'').'</td>';
				print '<td align="center">'.($obj->nb_running>0?$obj->nb_running:'').'</td>';
				print '<td align="center">'.($obj->nb_expired>0?$obj->nb_expired:'').'</td>';
				print '<td align="center">'.($obj->nb_closed>0 ?$obj->nb_closed:'').'</td>';
				print '<td class="nowrap" colspan="4" align="center"></td>';
			} elseif (in_array($val['type'], array('date','datetime','timestamp'))) {
				print $object->showOutputField($val, $key, $db->jdate($obj->$key), '');
			} elseif ($key == 'thirdparty_mail') {
				if (isSupplierContract($db, $obj->rowid))
					print '<td align="center">'.img_picto($langs->trans("NoMailForSupplier"), dol_buildpath('/contratplus/img/mail_ko_16.png', 1), '', 1);
				else if (!haveContactMail($db, $obj->socid))
					print '<td align="center">'.img_picto($langs->trans("NoMailContact"), dol_buildpath('/contratplus/img/mail_ko_16.png', 1), '', 1);
				else
					print '<td align="center">'.img_picto($langs->trans("Mail"), dol_buildpath('/contratplus/img/mail_ok_16.png', 1), '', 1);
			} elseif ($key == 'cron_status') {
				// input name a.id for checked & h.id for unchecked
				if (isAutomated($db, $obj->rowid))
				{
					print '<td align="center">';
					print '<a href="'. $_SERVER['PHP_SELF'] .'?action=unactivate&id=' . $obj->rowid . '">';
					print img_picto($langs->trans("Unactivate"), dol_buildpath('/contratplus/img/cron_ok_24.png', 1), '', 1);
					print '</a></td>';
				} else {
					print '<td align="center">';
					print '<a href="'. $_SERVER['PHP_SELF'] .'?action=activate&id=' . $obj->rowid . '">';
					print img_picto($langs->trans("Activate"), dol_buildpath('/contratplus/img/cron_ko_24.png', 1), '', 1);
					print '</a>';
					print '</td>';
				}
			} elseif ($key == 'private_note_display') {
				//private note
				print '<td align="center">';
				if ($pnote = contractHasPrivateNote($db, $obj->rowid)) {
					print img_picto($pnote, dol_buildpath('/contratplus/img/info_16.png', 1), '', 1);
				}
			} elseif ($key == 'assoc_thirdparty_comm_closed') {
				// Presence of a contract's third partie's command not closed
				print '<td align="center">';
				if (hasUnclosedCommand($db, $obj->rowid)) {
					print img_picto($langs->trans('AssocCommClosedOk'), dol_buildpath('/contratplus/img/comm_ok_20.png', 1), '', 1);
				} else {
					if (isSupplierContract($db, $obj->rowid)) {
						print img_picto($langs->trans('AssocCommClosedNoFour'), '', '', 1);
					} else {
						print img_picto($langs->trans('AssocCommClosedKo'), dol_buildpath('/contratplus/img/comm_20.png', 1), '', 1);
					}
				}
			} else print $object->showOutputField($val, $key, $obj->$key, '');
			if (!in_array($key, array('statuslist'))) {
				print '</td>';
			}
			if (! $i) $totalarray['nbfield']++;
			if (! empty($val['isameasure']))
			{
				if (! $i) $totalarray['pos'][$totalarray['nbfield']]='c.'.$key;
				$totalarray['val'][(in_array($key, $societe) ? 's.' : (in_array($key, $contrat) ? 'c.' : '')).$key] += $obj->$key;
			}
		}
	}
	// Extra fields
	include DOL_DOCUMENT_ROOT.'/core/tpl/extrafields_list_print_fields.tpl.php';
	// Fields from hook
	$parameters=array('arrayfields'=>$arrayfields, 'obj'=>$obj, 'i'=>$i, 'totalarray'=>&$totalarray);
	$reshook=$hookmanager->executeHooks('printFieldListValue', $parameters, $object);    // Note that $action and $object may have been modified by hook
	print $hookmanager->resPrint;
	// Action column
	print '<td class="nowrap center">';
	if ($massactionbutton || $massaction)   // If we are in select mode (massactionbutton defined) or if we have already selected and sent an action ($massaction) defined
	{
		$selected=0;
		if (in_array($obj->rowid, $arrayofselected)) $selected=1;
		print '<input id="cb'.$obj->rowid.'" class="flat checkforselect" type="checkbox" name="toselect[]" value="'.$obj->rowid.'"'.($selected?' checked="checked"':'').'>';
	}
	print '</td>';
	if (! $i) $totalarray['nbfield']++;

	print '</tr>';

	$i++;
}

// Show total line
if (isset($totalarray['pos']))
{
	print '<tr class="liste_total">';
	$i=0;
	while ($i < $totalarray['nbfield'])
	{
		$i++;
		if (! empty($totalarray['pos'][$i]))  print '<td class="right">'.price($totalarray['val'][$totalarray['pos'][$i]]).'</td>';
		else
		{
			if ($i == 1)
			{
				if ($num < $limit) print '<td class="left">'.$langs->trans("Total").'</td>';
				else print '<td class="left">'.$langs->trans("Totalforthispage").'</td>';
			}
			else print '<td></td>';
		}
	}
	print '</tr>';
}

// If no record found
if ($num == 0)
{
	$colspan=1;
	foreach($arrayfields as $key => $val) { if (! empty($val['checked'])) $colspan++; }
	print '<tr><td colspan="'.$colspan.'" class="opacitymedium">'.$langs->trans("NoRecordFound").'</td></tr>';
}


$db->free($resql);

$parameters=array('arrayfields'=>$arrayfields, 'sql'=>$sql);
$reshook=$hookmanager->executeHooks('printFieldListFooter', $parameters, $object);    // Note that $action and $object may have been modified by hook
print $hookmanager->resPrint;

print '</table>'."\n";
print '</div>'."\n";

print '</form>'."\n";

if (in_array('builddoc', $arrayofmassactions) && ($nbtotalofrecords === '' || $nbtotalofrecords))
{
	$hidegeneratedfilelistifempty=1;
	if ($massaction == 'builddoc' || $action == 'remove_file' || $show_files) $hidegeneratedfilelistifempty=0;

	require_once DOL_DOCUMENT_ROOT.'/core/class/html.formfile.class.php';
	$formfile = new FormFile($db);

	// Show list of available documents
	$urlsource=$_SERVER['PHP_SELF'].'?sortfield='.$sortfield.'&sortorder='.$sortorder;
	$urlsource.=str_replace('&amp;', '&', $param);

	$filedir=$diroutputmassaction;
	$genallowed=$user->rights->contratplus->read;
	$delallowed=$user->rights->contratplus->write;

	print $formfile->showdocuments('massfilesarea_mymodule', '', $filedir, $urlsource, 0, $delallowed, '', 1, 1, 0, 48, 1, $param, $title, '', '', '', null, $hidegeneratedfilelistifempty);
}

// End of page
llxFooter();
$db->close();
