<?php
//
// File generated by Dolibarr installer 12.0.0-alpha on Mar 13, 2020
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$dolibarr_main_url_root='https://sbx.dolibarr.kasimedicalsolutions.com/';
$dolibarr_main_document_root='/var/www/vhosts/h272310.web103.alfahosting-server.de/html/dolibarr_old3/htdocs';
$dolibarr_main_url_root_alt='/custom';
$dolibarr_main_document_root_alt='/var/www/vhosts/h272310.web103.alfahosting-server.de/html/dolibarr_old3/htdocs/custom';
$dolibarr_main_data_root='/var/www/vhosts/h272310.web103.alfahosting-server.de/html/dolibarr_old3/documents';
$dolibarr_main_db_host='127.0.0.1';
$dolibarr_main_db_port='3307';
$dolibarr_main_db_name='h272310_kmsdatabase';
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user='h272310_moise';
$dolibarr_main_db_pass='Kamerun!2019!';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='latin1';
$dolibarr_main_db_collation='latin1_german1_ci';
// Authentication settings
$dolibarr_main_authentication='dolibarr';

//$dolibarr_main_demo='autologin,autopass';
// Security settings
$dolibarr_main_prod='0';
$dolibarr_main_force_https='0';
$dolibarr_main_restrict_os_commands='mysqldump, mysql, pg_dump, pgrestore';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_instance_unique_id='bc098a4587db1821de94a32a66a6e5be';
$dolibarr_mailing_limit_sendbyweb='0';

//$dolibarr_lib_FPDF_PATH='';
//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_TCPDI_PATH='';
//$dolibarr_lib_ADODB_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_PHPEXCEL_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';
//$dolibarr_js_JQUERY_FLOT='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
